### ISSUE TITLE
Can't install from sbt, `common` submodule isn't published to maven

### ISSUE THREAD

**Issue by chadselph** [howardjohn/scala-server-lambda#1]
sbt requests https://repo1.maven.org/maven2/io/github/howardjohn/common_2.12/0.3.0/common_2.12-0.3.0.pom which wasn't published

**Comment by howardjohn** [comment]
Thanks for pointing that out, I will publish it right now. Should be up in 5-10 minutes

**Comment by howardjohn** [comment]
Should be published now. You'll have to update to 0.3.1 though. https://oss.sonatype.org/content/repositories/releases/io/github/howardjohn/http4s-lambda_2.12/0.3.1/

**Comment by chadselph** [comment]
thanks! great library by the way, it works really well
